import{i as h,a as i}from"./assets/vendor-eIIf_ydY.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))l(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const g of s.addedNodes)g.tagName==="LINK"&&g.rel==="modulepreload"&&l(g)}).observe(document,{childList:!0,subtree:!0});function r(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(o){if(o.ep)return;o.ep=!0;const s=r(o);fetch(o.href,s)}})();const a=e=>{h.error({iconUrl:"./img/bi_x-octagon.svg",position:"topRight",progressBarColor:"#B51B1B",message:e,messageColor:"#FAFAFB",backgroundColor:"#EF4040"})},p=e=>{h.error({iconUrl:"/img/bi_check2-circle.svg",position:"topRight",progressBarColor:"#326101",message:e,messageColor:"#FAFAFB",backgroundColor:"#59A10D"})},f=e=>{h.error({iconUrl:"./img/bi_exclamation-triangle.svg",position:"topRight",progressBarColor:"#BB7B10",message:e,messageColor:"#FAFAFB",backgroundColor:"#FFA000"})},n={form:document.querySelector(".form"),headerBtns:document.querySelector(".header-btns"),modalOverlay:document.querySelector(".modal-overlay"),modalForm:document.querySelector(".modal-form"),list:document.querySelector(".nodes-list"),loader:document.querySelector(".loader")},d=()=>{n.loader.classList.add("is-loading")},u=()=>{n.loader.classList.remove("is-loading")};i.defaults.baseURL="https://67d5879cd2c7857431f0aed3.mockapi.io/nodes/";const y=async()=>{try{return(await i.get("")).data}catch(e){throw console.log("Something went wrong with downloading nodes!"),e}},F=async e=>{try{return(await i.post("",e)).data}catch(t){throw console.log("Something went wrong with adding node!"),t}},N=async e=>{try{return(await i.get("",{params:{title:e}})).data}catch(t){throw console.log("Something went wrong with searching nodes!"),t}},w=async e=>{try{const t=await i.delete(`${e}`);return console.log(`Deleted node ${e}`),t.data}catch(t){throw console.log("Something went wrong with deleting node!"),t}},S=({id:e,title:t,description:r})=>`
    <li class="nodes-item" data-id="${e}">
          <h3 class="nodes-item-title">${t}</h3>
          <p class="nodes-item-description">${r}</p>
          <div class="nodes-item-btns">
            <button class="edit-node-btn" type="button" id="editNodeBtn">Edit</button>
            <button class="delete-node-btn" type="button" id="deleteNodeBtn">Delete</button>
          </div>
        </li>
    `,v=e=>{const t=e.map(r=>S(r)).join("");n.list.innerHTML=t},m=async()=>{const e=await y();v(e)},b=async e=>{e.preventDefault();const t=e.target.elements.nodeInput.value.trim(),r=e.target.elements.nodeTextarea.value.trim();if(!t||!r){f("Fill all fields");return}const l={title:t,description:r};try{d(),await F(l),await m(),p("Added new node!")}catch{a("Error adding note")}finally{c(),u(),n.modalForm.removeEventListener("submit",b),document.removeEventListener("keydown",L),n.modalOverlay.removeEventListener("click",B),e.target.reset()}},B=e=>{e.target===e.currentTarget&&c(),e.target.matches("#modalCloseBtn")&&c()},L=e=>{e.key==="Escape"&&c()},c=()=>{n.modalOverlay.classList.remove("is-open")},E=async()=>{try{d();const e=await y();if(!e){a("Nothing to delete");return}const t=await Promise.allSettled(e.map(({id:r})=>w(r)));console.log(t),await m()}catch{a("Something went wrong with deleting all Nodes!")}finally{u()}},k=async e=>{e.preventDefault();const t=e.target.elements.searchNode.value.trim();if(!t){f("Fill field");return}try{d();const r=await N(t);if(!r||!r.length){a("There is no such note matching your request.");return}v(r),p("Search is successful")}catch{a("Error with searching node!")}finally{u(),n.form.reset()}},C=async({target:e})=>{if(e.matches("#deleteNodeBtn"))try{d();const t=e.closest("li").dataset.id;await w(t),await m(),p("Node Successfully deleted!")}catch{a("Something went wrong with deleting node")}finally{u()}e.matches("#editNodeBtn")},A=({target:e})=>{e.matches("#deleteAllNodeBtn")&&E(),e.matches("#addNodeBtn")&&(n.modalOverlay.classList.add("is-open"),n.modalForm.addEventListener("submit",b),document.addEventListener("keydown",L),n.modalOverlay.addEventListener("click",B))};n.headerBtns.addEventListener("click",A);n.form.addEventListener("submit",k);n.list.addEventListener("click",C);m();
//# sourceMappingURL=index.js.map
